"""D-058 — WorkQueueRepo.list() filters assignee in SQL, not in Python after LIMIT.

Closes the silent under-reporting bug Hermes flagged: ``list(assignee="human",
limit=10)`` previously SELECT'd 10 rows ORDER BY created_at DESC and *then*
filtered by assignee in Python, so a queue with many recent agent items
silently returned 0 human items even when plenty existed.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Literal

from praxis.config.engagement import init_engagement
from praxis.workqueue.models import WorkItemPriority, WorkItemStatus, WorkItemType
from praxis.workqueue.repo import WorkQueueRepo


def _enqueue_many(
    repo: WorkQueueRepo,
    *,
    assignee: Literal["human", "agent"],
    count: int,
    title_prefix: str = "item",
) -> None:
    for i in range(count):
        repo.enqueue(
            type=WorkItemType.REVIEW_ARTIFACT,
            assignee=assignee,
            title=f"{title_prefix}-{assignee}-{i}",
            description="generated by D-058 test",
            priority=WorkItemPriority.MEDIUM,
        )


class TestAssigneeFilterCorrectness:
    def test_skewed_queue_still_returns_all_matching_humans(
        self,
        tmp_engagement: Path,
        tmp_home: Path,
    ) -> None:
        """The direct repro of the bug: 50 agent rows + 5 human rows.

        Before D-058, ``list(assignee="human", limit=10)`` SELECT'd the 10
        most recent rows (all agent) then Python-filtered → 0 results. With
        the fix, the assignee filter applies in SQL, so all 5 human items
        come back.
        """
        init_engagement(tmp_engagement, "Test")
        repo = WorkQueueRepo(tmp_engagement)

        # Enqueue 5 human first (oldest), then 50 agent (newest) — this
        # ordering is what triggered the bug because LIMIT picked up the
        # newest 10 (all agent) before the Python filter ran.
        _enqueue_many(repo, assignee="human", count=5)
        _enqueue_many(repo, assignee="agent", count=50)

        human_items = repo.list(assignee="human", limit=10)
        assert len(human_items) == 5, (
            f"Expected 5 human items, got {len(human_items)}. "
            "This is the D-058 regression — assignee was filtered after LIMIT."
        )
        assert all(i.assignee == "human" for i in human_items)

    def test_assignee_filter_combined_with_status(
        self,
        tmp_engagement: Path,
        tmp_home: Path,
    ) -> None:
        """Combined filters (status + assignee) compose correctly in SQL."""
        init_engagement(tmp_engagement, "Test")
        repo = WorkQueueRepo(tmp_engagement)

        _enqueue_many(repo, assignee="agent", count=3)
        _enqueue_many(repo, assignee="human", count=3)

        # All 6 items start in QUEUED; advance one of each to IN_PROGRESS
        # so the status filter has rows to exclude (QUEUED→DONE isn't a
        # valid direct transition; QUEUED→IN_PROGRESS is).
        all_items = repo.list(limit=50)
        agents = [i for i in all_items if i.assignee == "agent"]
        humans = [i for i in all_items if i.assignee == "human"]
        repo.transition(agents[0].id, WorkItemStatus.IN_PROGRESS)
        repo.transition(humans[0].id, WorkItemStatus.IN_PROGRESS)

        queued_agents = repo.list(status=WorkItemStatus.QUEUED, assignee="agent", limit=50)
        assert len(queued_agents) == 2
        assert all(i.assignee == "agent" for i in queued_agents)
        assert all(i.status == WorkItemStatus.QUEUED for i in queued_agents)

    def test_assignee_filter_returns_empty_when_no_matches(
        self,
        tmp_engagement: Path,
        tmp_home: Path,
    ) -> None:
        """Empty result for an assignee not present in the queue."""
        init_engagement(tmp_engagement, "Test")
        repo = WorkQueueRepo(tmp_engagement)

        _enqueue_many(repo, assignee="agent", count=5)

        assert repo.list(assignee="human", limit=50) == []


class TestMigrationBackfillsLegacyRows:
    def test_002_backfills_assignee_from_payload_json(
        self,
        tmp_engagement: Path,
        tmp_home: Path,
    ) -> None:
        """A row written before D-058 (assignee only in payload_json) gets
        backfilled into the new column by migration 002."""
        init_engagement(tmp_engagement, "Test")
        db_path = tmp_engagement / ".praxis" / "state" / "praxis.db"

        # Init runs all migrations; to simulate a "legacy" row we directly
        # NULL out the assignee column on a freshly-inserted row, then re-run
        # the backfill that the migration would have done. This is the
        # post-001 / pre-002 shape the migration must heal.
        repo = WorkQueueRepo(tmp_engagement)
        item = repo.enqueue(
            type=WorkItemType.REVIEW_ARTIFACT,
            assignee="agent",
            title="legacy",
            description="written before D-058",
            priority=WorkItemPriority.HIGH,
        )

        # Force the assignee column NULL — this is the state a pre-002 row
        # would be in after the column was added but before backfill.
        conn = sqlite3.connect(str(db_path))
        try:
            conn.execute("UPDATE workitems SET assignee = NULL WHERE id = ?", (item.id,))
            conn.commit()

            # Re-run the backfill SQL the migration uses.
            conn.execute(
                "UPDATE workitems SET assignee = json_extract(payload_json, '$.assignee') "
                "WHERE assignee IS NULL"
            )
            conn.commit()

            row = conn.execute("SELECT assignee FROM workitems WHERE id = ?", (item.id,)).fetchone()
            assert row[0] == "agent", f"backfill failed, got {row[0]!r}"
        finally:
            conn.close()

    def test_002_index_exists(
        self,
        tmp_engagement: Path,
        tmp_home: Path,
    ) -> None:
        """The new index on (assignee, status) must be created by migration 002."""
        init_engagement(tmp_engagement, "Test")
        db_path = tmp_engagement / ".praxis" / "state" / "praxis.db"

        conn = sqlite3.connect(str(db_path))
        try:
            indexes = conn.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='workitems'"
            ).fetchall()
            names = {row[0] for row in indexes}
            assert "idx_workitems_assignee" in names, (
                f"Migration 002 did not create idx_workitems_assignee. Found indexes: {names!r}"
            )
        finally:
            conn.close()
