"""Wake-cycle models — triggers, candidate tasks, reports, daily plans."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict


class WakeTrigger(StrEnum):
    """What caused a wake cycle to fire."""

    MANUAL = "manual"
    SCHEDULED = "scheduled"
    INBOX_EVENT = "inbox_event"
    WORKQUEUE_REPLY = "workqueue_reply"
    FILE_CHANGED = "file_changed"
    STARTUP = "startup"


class CandidateTask(BaseModel):
    """A potential task the orchestrator might execute during a wake."""

    model_config = ConfigDict(extra="forbid")

    task_type: str
    description: str
    score: float = 0.0
    related_ids: list[str] = []
    metadata: dict[str, object] = {}


class StateChange(BaseModel):
    """A change to engagement state observed between two wake cycles."""

    model_config = ConfigDict(extra="forbid")

    entity_type: Literal["decision", "constraint", "assumption", "risk", "question"]
    entity_id: str
    change: Literal["created", "answered"]
    title: str
    timestamp: datetime


class WakeReport(BaseModel):
    """Summary of a single wake-cycle execution."""

    model_config = ConfigDict(extra="forbid")
    schema_version: Literal[1] = 1

    started_at: datetime
    ended_at: datetime
    trigger: WakeTrigger
    state_changes_observed: list[str] = []
    state_changes_since_last_wake: list[StateChange] = []
    tasks_considered: list[str] = []
    tasks_executed: list[str] = []
    workitems_created: list[str] = []
    audit_event_count: int = 0
    tokens_used: int = 0
    notes: str | None = None


class DailyPlan(BaseModel):
    """Daily plan summary generated by the orchestrator."""

    model_config = ConfigDict(extra="forbid")
    schema_version: Literal[1] = 1

    date: str
    summary: str
    recent_activity: list[str] = []
    top_workitems: list[str] = []
    open_blockers: list[str] = []
    generated_at: datetime
